### ISSUE TITLE
Default for gmp/int kind?

### ISSUE THREAD

**Issue by githwxi** [sparverius/Temptory-Release#1]
One thought:

If one issues 'make', a default can be chosen (e.g., 'make' is set to be equivalent to 'make int').
Or a warning/error message can be issued.

**Comment by sparverius** [comment]
Makefile is now a symlink to [Makefile_build](https://github.com/sparverius/Temptory-Release/blob/master/Makefile_build). Now calling `make` will build both release kinds. Is this what you had in mind?

**Comment by githwxi** [comment]
This is good. Thanks!
