### ISSUE TITLE
Temptory package seems bloated

### ISSUE THREAD

**Issue by githwxi** [sparverius/Temptory-Release#5]
When I released ATS-Postiats last time, its size was about 4.5M. Temptory is of size 17M. Should be interesting to investigate a bit.

**Comment by sparverius** [comment]
Oh yes, it seems that the c files generated by atsopt into srcgen/BUILD were copied over to CBOOT and not cleaned up after.

**Comment by sparverius** [comment]
Also .git directory was not removed

**Comment by githwxi** [comment]
Good that you found it! Now the size of the entire package seems to be correct.
